### PR TITLE
add news update regarding fosshost going EOL

### PR DESCRIPTION
**Pull request by TheLostProbe**
also adds a message on the home page about it

screenshots:
image
image

### CODE REVIEW

**Comment by 375gnu** [comment]
Why do we need this?

**Comment by TheLostProbe** [comment]
if fosshost, and subsequently the website, is going offline, then users should know about it. else they get confused as to why their favourite planetarium program's website is not available. it's fairly common practice

though even I think the red I did was a bit unnecessary but it's eye-catching and will alert the viewer quicker than if it was transparent

**Comment by TheLostProbe** [comment]
fosshost has announced that their datacenter will be operational at least until the end of the year, so i want to reword this

**Comment by TheLostProbe** [comment]
@375gnu, this better?
image
image

**Comment by TheLostProbe** [comment]
btw, tell me when you are ready to merge so i can update this date
image

**Comment by TheLostProbe** [comment]
ready when you are

**Pull request merged**
