### PR TITLE
update gnu/linux download guides

### PR DESCRIPTION
**Pull request by TheLostProbe**
supersedes #35
screenshots:
image
_updated guides for different distros_
image
_updated download page_

### CODE REVIEW

**Comment by TheLostProbe** [comment]
@375gnu apologies for the mention, but please check this and merge

**Comment by TheLostProbe** [comment]
converted to draft since the install instructions uses outdated links, will update the links and have it checked later

**Comment by TheLostProbe** [comment]
i think i found where the latest 1.7.0 appimages are, i will test this later and see if they work. @munix9 can you confirm that these are the right ones?
https://download.opensuse.org/repositories/home:/munix9:/unstable/AppImage/

**Comment by munix9** [comment]
> i think i found where the latest 1.7.0 appimages are, i will test this later and see if they work. @munix9 can you confirm that these are the right ones? https://download.opensuse.org/repositories/home:/munix9:/unstable/AppImage/

Yes, see also  
https://github.com/CelestiaProject/Celestia/blob/master/INSTALL.md?plain=1#L49  
https://github.com/CelestiaProject/Celestia/issues/333

**Comment by TheLostProbe** [comment]
should be good to go now. i dont trust that merge commit though
image
image

**Pull request merged**
