### PR TITLE
Update back.jpg

### PR DESCRIPTION
**Pull request by TheLostProbe**
i noticed that the current back.jpg is a screenshot from an older version, and so the textures are out of date. it might be a good idea to update it to a screenshot with the current textures, but its your choice.

i worry that the artifacting seen on the side of the earth may be too visible. also, you can use the [slightly older updated back.jpg](https://raw.githubusercontent.com/TheLostProbe/www/c4d00cf68cfb6de75a168996d31f7fde7fdcb308/images/back.jpg) i made, but the artifacting is likely more visible on that version. again, its your choice

note: ignore the other commits linked below, you only need to focus on 20ab6c3. i have no clue how to remove them lmao

### CODE REVIEW

**Comment by levinli303** [comment]
please rebase on top of latest master branch

**Comment by TheLostProbe** [comment]
sorry, im new to github, could you point me in the right direction? and before you ask, yes i did google what rebasing is and i still havent got a clue

**Comment by levinli303** [comment]
you can probably do it using "Sync Fork" if you are using web only. Go to your [own repo](https://github.com/TheLostProbe/www) an options should be there
Screen Shot 2022-08-02 at 15 12 29

**Comment by TheLostProbe** [comment]
yeah i tried that and it says "no new commits to fetch"

**Comment by levinli303** [comment]
can you set "Allow editing from maintainers" on this PR I can help you change it.

**Comment by TheLostProbe** [comment]
it is on
image

**Comment by levinli303** [comment]
I'm ok with merging it. tagging @CelestiaProject/devs just in case.

**Comment by TheLostProbe** [comment]
yeah 375gnu might want to review it

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
